# -*- ruby -*-

require 'rubygems'
require 'hoe'
require 'hoe/signing'
require 'factory_girl'

Hoe.plugin :yard
Hoe.plugin :rcov

Hoe.spec('singus') do
  self.developer('FIX', 'FIX@server.com')

  self.rspec_options += ['--colour', '--format', 'd']

  self.yard_options += ['--markup', 'markdown', '--protected']
  self.remote_yard_dir = '/'

  self.extra_dev_deps += [
    ['rspec'],
    ['yard']
  ]
end

# vim: syntax=ruby
