# -*- ruby -*-

require 'rubygems'
require 'hoe'
require 'hoe/signing'
require 'rspec'

Hoe.plugin :yard
Hoe.plugin :bundler
Hoe.plugin :doofus

Hoe.spec('singus') do
  self.developer('Ville Peurala', 'ville.peurala@gmail.com')

  self.rspec_options += ['--colour', '--format', 'd']

  self.yard_options += ['--markup', 'markdown', '--protected']
  self.remote_yard_dir = '/'

  self.extra_dev_deps += [
    ['rspec'],
    ['yard'],
    ['factory_girl'],
    ['rcov'],
    ['autotest']
  ]
end

desc "Run specs with rcov"
RSpec::Core::RakeTask.new("spec:rcov") do |t|
  t.rcov = true
  t.rcov_opts = ['--exclude', '/gems/,jsignal_internal']
end

# vim: syntax=ruby
